### ISSUE TITLE
Assertion error during open-images training

### ISSUE THREAD

**Issue by akshitac8** [hbdat/cvpr20_LESA#3]
Hello Dat,
The total length of the top unseen is 400 but it's 399 at L55 of the training file.
It would be great if you could let me know the correct number.

Thanks in advance,
Akshita

**Comment by hbdat** [comment]
Hi Akshita,

Thanks for carefully inspecting the code.
The assertion should be 400 as there are 400 labels in the csv file.
I have corrected this in my latest commit (could not recall why 399 appears there).

Best,
Dat

**Comment by akshitac8** [comment]
Thank you @hbdat

**Comment by akshitac8** [comment]
@hbdat I also wanted to ask how many numbers of images do you have after masking for ZSL evaluation for open-images?

**Comment by hbdat** [comment]
Hi @akshitac8,

The number of testing samples, used to computed mAP scores for ZSL and GZSL, are different across different labels.
This is because a sample could lack annotation for label ‘A’ but include annotation for label ‘B’. 
Thus, such sample is only excluded when computing AP for ‘A’ but will be included for ‘B’.

We construct unseen labels such that they have at least 75 annotated samples in test set for reliable evaluation.
