### ISSUE TITLE
 Augmenting 1 in attention function

### ISSUE THREAD

**Issue by Jiany-Zhang** [hbdat/cvpr20_LESA#4]
Thank you for sharing the useful code.
I have a question about augmenting 1 in attention function in model_share_attention.py. I don't understand the significance of augmenting one or augmenting zero in training. These calculations are also not mentioned in the paper.
https://github.com/hbdat/cvpr20_LESA/blob/23fe4302aec1d5e18fb3793497bbee58e795f40a/core/model_share_attention.py#L100-L114
Thank you for your answer

**Comment by hbdat** [comment]
Hi @Jiany-Zhang,

Thanks for your interest in the project.
The augment_1 here is just a trick to implement a fully connected layer in a neural network using a single matrix multiplication instead of multiplication and addition. 
Here we use MLP to parametrized the shared attention, which we mentioned at the beginning of equation 5 in the paper as 
``To learn and infer \alpha_m(F_i), we use a simple two-layer neural network model``

To provide explanation about this trick, I have composed a short pdf (as github does not support latex annotation):
https://github.com/hbdat/cvpr20_LESA/blob/master/doc/augment_1_trick.pdf

Best,
Dat

**Comment by Jiany-Zhang** [comment]
Thank you @hbdat
